# name: CI

on:
  push:
  pull_request:

jobs:
  library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Vet
        run: go vet ./...
      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          install-go: false
      - name: Test (race)
        run: go test -race ./...

  integration-tests:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: tests/go.mod
        
      - name: Vet (integration tag)
        working-directory: tests
        run: go vet -tags integration ./...
    
      - name: Install docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
    
      - name: Test (integration tag)
        working-directory: tests
        run: |
            sudo chown -R 1000:root .test-*
            sudo chmod -R 777 .test-*
            sed -i "s/1000:1000/$(id -u):$(id -g)/g" compose.yml
            docker compose pull
            docker compose build gopbs
            go test -tags integration ./

      - name: Go tests
        uses: robherley/go-test-action@v1
        with:
            moduleDirectory: tests
            testArguments: -tags integration
            cover: true
